import json
import os
import requests

def summarize_with_ai(analysis_data):
    """
    Calls OpenAI API to generate a repository summary if OPENAI_API_KEY is present,
    otherwise falls back to a mock summary.
    """
    api_key = os.environ.get("OPENAI_API_KEY")

    if api_key:
        try:
            headers = {
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json"
            }
            prompt = f"Analyze this repository structure and provide an architectural summary, a brief onboarding guide, and developer documentation:\n{json.dumps(analysis_data)}"
            payload = {
                "model": "gpt-4",
                "messages": [
                    {"role": "system", "content": "You are an expert AI repository maintainer. Generate high quality documentation."},
                    {"role": "user", "content": prompt}
                ],
                "temperature": 0.3
            }
            response = requests.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, timeout=30)
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"]
        except Exception as e:
            print(f"Failed to generate summary with API: {e}. Falling back to local generation.")
            # Fall through to mock

    # We will generate a mock summary based on the analysis data
    frameworks = analysis_data.get("frameworks", [])
    files = len(analysis_data.get("files", []))
    dirs = len(analysis_data.get("directories", []))

    summary = f"This repository contains {files} files across {dirs} directories.\n\n"

    if frameworks:
        summary += f"Detected Frameworks: {', '.join(frameworks)}\n\n"

    summary += "### Architecture Overview\n"
    summary += "The project is structured with standard directories. Dependencies are managed via standard package files. "
    summary += "This summary is auto-generated by the AI Documentation Agent based on the latest codebase scan.\n"

    return summary

def run_doc_agent(analysis_file="repo_analysis.json", output_file="ai_summary.md"):
    """Runs the AI documentation agent to generate an architectural summary."""
    try:
        with open(analysis_file, 'r') as f:
            data = json.load(f)
    except FileNotFoundError:
        print(f"Error: {analysis_file} not found.")
        return

    summary = summarize_with_ai(data)

    with open(output_file, 'w') as f:
        f.write(summary)

    print(f"AI Documentation Summary generated at {output_file}")

if __name__ == "__main__":
    run_doc_agent()
